name: Release Package

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write # for publishing release to GitHub
      packages: write # for publishing package to NPM
      id-token: write # for trusted publishing to NPM
    uses: aws-geospatial/github-workflows-for-amazon-location/.github/workflows/node-release.yml@main
